### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by zdenop** [comment]
This docs is based on stable branch (3.05) or dev (master aka 4.x)?

**Comment by stweil** [comment]
It's based on the Git master branch.

**Comment by stweil** [comment]
See https://ub-mannheim.github.io/tesseract/ for a reference. It would also be possible to move the whole documentation into a subdirectory and add a new index.html in the web root, so documentation could be shown for all important branches.

**Comment by stweil** [comment]
I now added a `README.md` file for GitHub.

**Comment by stweil** [comment]
It looks like the current documentation was built from [3.04.00](http://tesseract-ocr.github.io/a00681.html#a1010f99edacb96c8fe0dbcb59c37978c).

**Comment by Shreeshrii** [comment]
> It would also be possible to move the whole documentation into a subdirectory and add a new index.html in the web root, so documentation could be shown for all important branches.

I think this might be the recommended method, since it would be helpful to have documentation for both 3.05 and 4.0 (master) branches.

I agree that we don't need updates to documenation for every commit. But once this is setup, you could consider updates after every n commits (since tagging of releases happens infrequently while changes to code are more frequent now).

**Comment by Shreeshrii** [comment]
@stweil For now, I am adding link to  https://ub-mannheim.github.io/tesseract/  on the wiki page for documentation.

**Comment by stweil** [comment]
@zdenop, should I update the PR to include documentation for both 3.05 and master? What about the current documentation fo 3.04? Should it be kept or replaced by 3.05?

**Comment by Shreeshrii** [comment]
@zdenop is planning a new release - 3.05.01 within next few days. You can plan to include documentation as of that day.

**Comment by stweil** [comment]
I changed the PR to include both the current documentation (which can be replaced by 3.05.01 later) and the latest documentation based on git master.

**Comment by Shreeshrii** [comment]
Thanks!

@stweil During next update please add a H1 header (same text as title) to the index.html.

**Pull request merged**
